// Generated by gencpp from file mir_nav_interface/LaserCloudList.msg
// DO NOT EDIT!


#ifndef MIR_NAV_INTERFACE_MESSAGE_LASERCLOUDLIST_H
#define MIR_NAV_INTERFACE_MESSAGE_LASERCLOUDLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mir_nav_interface/LaserCloud.h>

namespace mir_nav_interface
{
template <class ContainerAllocator>
struct LaserCloudList_
{
  typedef LaserCloudList_<ContainerAllocator> Type;

  LaserCloudList_()
    : clouds()  {
    }
  LaserCloudList_(const ContainerAllocator& _alloc)
    : clouds(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::mir_nav_interface::LaserCloud_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mir_nav_interface::LaserCloud_<ContainerAllocator> >::other >  _clouds_type;
  _clouds_type clouds;





  typedef boost::shared_ptr< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> const> ConstPtr;

}; // struct LaserCloudList_

typedef ::mir_nav_interface::LaserCloudList_<std::allocator<void> > LaserCloudList;

typedef boost::shared_ptr< ::mir_nav_interface::LaserCloudList > LaserCloudListPtr;
typedef boost::shared_ptr< ::mir_nav_interface::LaserCloudList const> LaserCloudListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_nav_interface::LaserCloudList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mir_nav_interface::LaserCloudList_<ContainerAllocator1> & lhs, const ::mir_nav_interface::LaserCloudList_<ContainerAllocator2> & rhs)
{
  return lhs.clouds == rhs.clouds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mir_nav_interface::LaserCloudList_<ContainerAllocator1> & lhs, const ::mir_nav_interface::LaserCloudList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mir_nav_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03378f16abdd7f192fda69da6535d6f5";
  }

  static const char* value(const ::mir_nav_interface::LaserCloudList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03378f16abdd7f19ULL;
  static const uint64_t static_value2 = 0x2fda69da6535d6f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_nav_interface/LaserCloudList";
  }

  static const char* value(const ::mir_nav_interface::LaserCloudList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LaserCloud[] clouds\n"
"\n"
"================================================================================\n"
"MSG: mir_nav_interface/LaserCloud\n"
"# scanner\n"
"uint8 BACK_SCANNER=1\n"
"uint8 FRONT_SCANNER=2\n"
"uint8 RIGHT_SCANNER=3\n"
"\n"
"sensor_msgs/PointCloud2 cloud_data\n"
"geometry_msgs/Pose origin\n"
"geometry_msgs/Transform odom_to_base\n"
"uint8 scanner\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mir_nav_interface::LaserCloudList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clouds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaserCloudList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_nav_interface::LaserCloudList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_nav_interface::LaserCloudList_<ContainerAllocator>& v)
  {
    s << indent << "clouds[]" << std::endl;
    for (size_t i = 0; i < v.clouds.size(); ++i)
    {
      s << indent << "  clouds[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mir_nav_interface::LaserCloud_<ContainerAllocator> >::stream(s, indent + "    ", v.clouds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_NAV_INTERFACE_MESSAGE_LASERCLOUDLIST_H
